Update for bionic and 2018

diff --git a/setup/setup b/setup/setup
--- a/setup/setup
+++ b/setup/setup
@@ -1,67 +1,52 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # Basic stuff to setup an intial system
 # Joshua Powers <mrpowersj@gmail.com>
-set -ux
+set -eux
 
-getent hosts us.archive.ubuntu.com
-rc="$?"
-if [ "$rc" != "0" ]; then
-	echo "Network not active."
+getent hosts us.archive.ubuntu.com || {
+	echo "Network is not active."
 	exit 1
-fi
+}
 
 APT=(
+	ansible
+	ansible-lint
 	apt-rdepends
 	asciinema
 	bsdtar
-	byobu
+	build-essential
 	bzr
-	bzr-stats
 	curl
 	devscripts
 	ethtool
-	fonts-hack-ttf
 	git
-	gnome-tweak-tool
 	gnupg
-	google-chrome-stable
+    chromium-browser	
 	gparted
 	htop
+	influxdb-client
+	intel-microcode
 	ipmitool
-	jekyll
 	jq
 	libavcodec-extra
 	libde265-0
-	lxd
 	meld
-	mutt
 	network-manager-openvpn-gnome
 	nfs-common
 	openvpn
 	pastebinit
 	patch
-	pycodestyle
-	pydocstyle
-	pyflakes3
-	pylint3
-	python3
-	python3-flake8
-	python3-git
 	qemu-kvm
 	sbuild
-	schroot
 	shellcheck
-	snapcraft
 	squid-deb-proxy-client
 	stow
-	sublime-text
 	tox
 	tree
 	ubuntu-dev-tools
 	uvtool
 	vim
 	virt-manager
-	vlc
 	zfsutils-linux
 )
 
@@ -80,22 +65,22 @@ UNINSTALL=(
 )
 
 #####################################################################
-# APT Setup
-wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
-ppa_chrome="/etc/apt/sources.list.d/google-chrome.list"
-if [ ! -e "$ppa_chrome" ]; then
-	echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a "$ppa_chrome" > /dev/null
-fi
+# Clean sources.list
 
-wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
-ppa_sublime="/etc/apt/sources.list.d/sublime-text.list"
-if [ ! -e "$ppa_sublime" ]; then
-	echo "deb https://download.sublimetext.com/ apt/dev/" | sudo tee -a "$ppa_sublime" > /dev/null
-fi
+RELEASE=$(lsb_release -c -s)
 
-apt_translations="/etc/apt/apt.conf.d/99translations"
-if [ ! -e "$apt_translations" ]; then
-	echo 'Acquire::Languages "none";' | sudo tee -a "$apt_translations" > /dev/null
+if true ; then
+    cat <<- EOF | sudo tee /etc/apt/sources.list
+	deb http://us.archive.ubuntu.com/ubuntu/ $RELEASE main restricted universe multiverse 
+	deb-src http://us.archive.ubuntu.com/ubuntu/ $RELEASE main restricted universe multiverse 
+
+	deb http://us.archive.ubuntu.com/ubuntu/ $RELEASE-security main restricted universe multiverse 
+	deb http://us.archive.ubuntu.com/ubuntu/ $RELEASE-updates main restricted universe multiverse 
+	deb http://us.archive.ubuntu.com/ubuntu/ $RELEASE-backports main restricted universe multiverse 
+	deb-src http://us.archive.ubuntu.com/ubuntu/ $RELEASE-security main restricted universe multiverse 
+	deb-src http://us.archive.ubuntu.com/ubuntu/ $RELEASE-updates main restricted universe multiverse 
+	deb-src http://us.archive.ubuntu.com/ubuntu/ $RELEASE-backports main restricted universe multiverse 
+	EOF
 fi
 
 #####################################################################
@@ -107,13 +92,16 @@ sudo apt-get install -y "${APT[@]}"
 sudo apt-get purge -y "${UNINSTALL[@]}"
 
 #####################################################################
-# Dotfiles
-pushd dotfiles
-for dir in */; do
-	echo "Setting up $dir"
-	stow -v -t "$HOME" "$dir"
-done
-popd
+# Install snaps
+sudo snap install aws-cli --classic
+sudo snap install git-ubuntu --classic
+sudo snap install hugo
+sudo snap install lxd
+sudo snap install multipass --classic --beta
+sudo snap install spotify
+sudo snap install ustriage --classic
+sudo snap install vlc
+sudo snap install vscode --classic
 
 #####################################################################
 # Configure gnome
@@ -132,19 +120,26 @@ fi
 gsettings set org.gnome.desktop.interface clock-show-date true
 gsettings set org.gnome.desktop.interface clock-show-seconds true
 gsettings set org.gnome.desktop.interface show-battery-percentage true
+gsettings set org.gnome.desktop.notifications show-in-lock-screen false
+gsettings set org.gnome.desktop.notifications show-banners false
 gsettings set org.gnome.desktop.peripherals.mouse natural-scroll false
 gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false
-gsettings set org.gnome.shell favorite-apps "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'google-chrome.desktop', 'sublime_text.desktop', 'org.gnome.gedit.desktop', 'vlc.desktop', 'org.gnome.Calculator.desktop']"
+gsettings set org.gnome.shell favorite-apps "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'firefox.desktop', 'vscode_vscode.desktop', 'spotify_spotify.desktop', 'org.gnome.gedit.desktop', 'vlc_vlc.desktop', 'org.gnome.Calculator.desktop', 'gnome-control-center.desktop', 'org.gnome.Screenshot.desktop', 'chromium-browser.desktop']"
 gsettings set org.gtk.Settings.FileChooser show-hidden true
 gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
+gsettings set org.gnome.nautilus.list-view default-zoom-level 'small'
 gsettings set org.gnome.nautilus.icon-view default-zoom-level 'small'
-
-mkdir -p "$HOME"/Pictures/backgrounds
-cp "$PWD"/img/background.png "$HOME"/Pictures/backgrounds
-gsettings set org.gnome.desktop.background picture-uri file:///"$HOME"/Pictures/backgrounds/background.png
+gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 24
+gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
+gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true
+gsettings set org.gnome.shell.extensions.dash-to-dock intellihide false
+gsettings set org.gnome.desktop.wm.keybindings switch-applications "[]"
+gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "[]"
+gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
+gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Shift><Alt>Tab']"
 
 #####################################################################
-# Grub
+# Customize Grub
 sudo sed -i 's/GRUB_HIDDEN_TIMEOUT=0/GRUB_HIDDEN_TIMEOUT=/' /etc/default/grub
 sudo sed -i 's/GRUB_TIMEOUT=10/GRUB_TIMEOUT=3/' /etc/default/grub
 sudo sed -i 's/quiet splash//' /etc/default/grub
@@ -154,18 +149,11 @@ sudo update-grub
 #####################################################################
 # Terminal
 # Theme
-wget -O monokai https://raw.githubusercontent.com/Mayccoll/Gogh/master/themes/monokai-dark.sh
-chmod +x monokai
-./monokai
-rm monokai
-
-# Settings
-profile_uuid=$(gsettings get org.gnome.Terminal.ProfilesList default | sed s/\'//g)
-key="org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile_uuid/"
-gsettings set "$key" use-system-font false
-gsettings set "$key" allow-bold true
-gsettings set "$key" scrollback-unlimited true
-gsettings set "$key" font "Hack Regular 12"
+THEME=freya
+wget -O "$THEME" https://raw.githubusercontent.com/Mayccoll/Gogh/master/themes/"$THEME".sh
+chmod +x "$THEME"
+./"$THEME"
+rm "$THEME"
 
 #####################################################################
 # gedit
@@ -173,7 +161,6 @@ gsettings set org.gnome.gedit.preferences.editor auto-save false
 gsettings set org.gnome.gedit.preferences.editor bracket-matching true
 gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
 gsettings set org.gnome.gedit.preferences.editor display-right-margin true
-gsettings set org.gnome.gedit.preferences.editor editor-font "Hack 12"
 gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
 gsettings set org.gnome.gedit.preferences.editor insert-spaces true
 gsettings set org.gnome.gedit.preferences.editor right-margin-position 72
@@ -183,34 +170,20 @@ gsettings set org.gnome.gedit.preferences.editor use-default-font false
 gsettings set org.gnome.gedit.preferences.ui max-recents 20
 
 #####################################################################
-# sublime
-# Install Package Control
-dir_sublime_pkgs="$HOME"/.config/sublime-text-3/Installed\ Packages/
-if [ ! -e "$dir_sublime_pkgs"/Package\ Control.sublime-package ]; then
-	mkdir -p "$dir_sublime_pkgs"
-	wget -NP "$dir_sublime_pkgs" https://packagecontrol.io/Package%20Control.sublime-package
-fi
-
-# Install Settings + Additonal Packages
-dir_sublime_settings="$HOME"/.config/sublime-text-3/Packages/User/
-mkdir -p "$dir_sublime_settings"
-git clone https://github.com/gerardroche/sublime-molokai.git ~/.config/sublime-text-3/Packages/molokai
-cp "$PWD"/sublime/Preferences.sublime-settings "$dir_sublime_settings"
-cp "$PWD"/sublime/Package\ Control.sublime-settings "$dir_sublime_settings"
-
-#####################################################################
 # lxd
-sudo lxd init --auto
+ip link show lxdbr0 || sudo lxc network create lxdbr0 ipv6.address=none ipv4.address=192.168.9.1/24 ipv4.nat=true
+sudo lxd init --auto --storage-backend zfs
+sudo usermod --append --groups lxd powersj
 
 #####################################################################
 # fstab
-if ! grep -q z170 /etc/fstab; then
-	echo '192.168.3.2:/z170 /home/powersj/Backup    nfs   auto,nofail,noatime,nolock,intr,tcp,actimeo=1800  0   0' |
+if ! grep -q x1 /etc/fstab; then
+	echo '192.168.1.10:/x1 /home/powersj/Backup    nfs   auto,nofail,noatime,nolock,intr,tcp,actimeo=1800  0   0' |
 		sudo tee -a /etc/fstab > /dev/null
 fi
 
 if ! grep -q nas /etc/fstab; then
-	echo '192.168.3.2:/nas /home/powersj/NAS    nfs   auto,nofail,noatime,nolock,intr,tcp,actimeo=1800  0   0' |
+	echo '192.168.1.10:/nas /home/powersj/NAS    nfs   auto,nofail,noatime,nolock,intr,tcp,actimeo=1800  0   0' |
 		sudo tee -a /etc/fstab > /dev/null
 fi
 
